[supervisord]
nodaemon=true

[program:apt-cacher-ng]
command=/usr/sbin/apt-cacher-ng -c /etc/apt-cacher-ng ForeGround=1
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:verdaccio]
command=/usr/local/bin/verdaccio --config /etc/swe-cache/npm/verdaccio.yaml
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:athens]
command=/bin/sh -ec 'export ATHENS_STORAGE_TYPE=disk ATHENS_DISK_STORAGE_ROOT=/var/lib/athens ATHENS_PORT=:{{ .GoPort }} ATHENS_GO_BINARY_ENV_VARS="GOPROXY=https://proxy.golang.org,direct" ATHENS_LOG_LEVEL=warn; exec /usr/local/bin/athens-proxy'
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:distribution]
command=/usr/local/bin/registry serve /etc/docker/registry/config.yml
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
